# version: "3.8"

# services:
#   postgres:
#     image: postgres:16
#     container_name: postgres-gym
#     restart: always
#     environment:
#       APOSTGRES_USER: gym
#       POSTGRES_PASSWORD: gym12345
#       POSTGRES_DB: gym-db
#     ports:
#       - "8080:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data:


version: "3.9"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver2022
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "TuPassword123"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped